services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: devbossmail-app
        container_name: devbossmail-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - devbossmail-network

    nginx:
        image: nginx:alpine
        container_name: devbossmail-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - devbossmail-network

    db:
        image: mysql:8.0
        container_name: devbossmail-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - devbossmail-network

    redis:
        image: redis:alpine
        container_name: devbossmail-redis
        restart: unless-stopped
        networks:
            - devbossmail-network

    mailpit:
        image: axllent/mailpit
        container_name: devbossmail-mailpit
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - devbossmail-network

networks:
    devbossmail-network:
        driver: bridge

volumes:
    db-data:
